# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09669220034d4cd218c6dbbffb9e22f3168456dfc0d38fa574aee60053a9ab45f1d28ed11c7014200f130c7bc0b2ae2a31e96b7e9ada84b7b74ae0647cfe8c0d

test:
  secret_key_base: fb1972dd4a8ff5e6376569f3a5d793870972d37bee5e356e5f2773fc0d57f77454012a3b973e8967fcd80f77ff9c2380fffcc11352c2bee37b1349eac98d2919

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
